# Generated by Django 5.2.5 on 2025-08-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preprocessed_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.FloatField()),
                ('age', models.FloatField()),
                ('weekly_study_time', models.FloatField()),
                ('absences', models.FloatField()),
                ('average_grade', models.FloatField()),
                ('behavior', models.FloatField()),
                ('final_outcome', models.CharField()),
                ('gender_Male', models.FloatField()),
            ],
        ),
    ]
