# Generated by Django 5.2.5 on 2025-08-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_remove_preprocessed_data_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessed_data',
            name='absences',
        ),
        migrations.RemoveField(
            model_name='preprocessed_data',
            name='average_grade',
        ),
        migrations.RemoveField(
            model_name='preprocessed_data',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='preprocessed_data',
            name='final_outcome',
        ),
        migrations.RemoveField(
            model_name='preprocessed_data',
            name='gender_Male',
        ),
        migrations.RemoveField(
            model_name='preprocessed_data',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='preprocessed_data',
            name='weekly_study_time',
        ),
    ]
