# Generated by Django 5.2.5 on 2025-08-22 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_remove_preprocessed_data_absences_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessed_data',
            name='absences',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='preprocessed_data',
            name='age',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='preprocessed_data',
            name='average_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='preprocessed_data',
            name='behavior',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='preprocessed_data',
            name='final_outcome',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='preprocessed_data',
            name='gender_Male',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='preprocessed_data',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preprocessed_data',
            name='weekly_study_time',
            field=models.FloatField(default=0),
        ),
    ]
