# Generated by Django 5.2.5 on 2025-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_preprocessed_data_absences_preprocessed_data_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessed_data',
            name='final_outcome',
            field=models.FloatField(default=''),
        ),
    ]
